.PHONY: clean All

All:
	@echo "----------Building project:[ Section_3 - Debug ]----------"
	@cd "Section_3" && "$(MAKE)" -f  "Section_3.mk"
clean:
	@echo "----------Cleaning project:[ Section_3 - Debug ]----------"
	@cd "Section_3" && "$(MAKE)" -f  "Section_3.mk" clean
