.PHONY: clean All

All:
	@echo "----------Building project:[ Section_1 - Debug ]----------"
	@cd "Section_1" && "$(MAKE)" -f  "Section_1.mk"
clean:
	@echo "----------Cleaning project:[ Section_1 - Debug ]----------"
	@cd "Section_1" && "$(MAKE)" -f  "Section_1.mk" clean
