.PHONY: clean All

All:
	@echo "----------Building project:[ Section_8 - Debug ]----------"
	@cd "Section_8" && "$(MAKE)" -f  "Section_8.mk"
clean:
	@echo "----------Cleaning project:[ Section_8 - Debug ]----------"
	@cd "Section_8" && "$(MAKE)" -f  "Section_8.mk" clean
